
export const ALL_PRODUCT_REQUEST="ALL_PRODUCT_REQUEST";
export const ALL_PRODUCT_SUCCESS="ALL_PRODUCT_SUCCESSS";
export const ALL_PRODUCT_FAIL="ALL_PRODUCT_FAIL";

export const ALL_CATEGORY_REQUEST="ALL_CATEGORY_REQUEST";
export const ALL_CATEGORY_SUCCESS="ALL_CATEGORY_SUCCESSS";
export const ALL_CATEGORY_FAIL="ALL_CATEGORY_FAIL";

export const ADD_TO_CART ="ADD_TO_CART";
export const REMOVE_FROM_CART="REMOVE_FROM_CART";

export const CLEAR_ERRORs= "CLEAR_ERRORs";
